Indev
FirewallGR/Algebra-of-Polynomials pull request #8
Opened 2023-03-31 20:21 UTC by Firstbourne

Added realization of stack.cpp, monom.cpp
Fixed some minor bugs in stack.h, monom.h, treeh.h

2023-04-01 10:37 UTC, FirewallGR commented on Algebra-of-Polynomials/libs/Functional/lib_Monom/Monom.cpp
> +        result.powers[i] /= x;
Зачем делить степень на число?

2023-04-03 20:03 UTC, FirewallGR requested changes

2023-04-03 20:03 UTC, FirewallGR commented on Algebra-of-Polynomials/libs/Functional/lib_Monom/Monom.cpp
> +        throw std::invalid_argument("Different number of variables");
@Firstbourne Почему нельзя перемножать так?

2023-04-03 20:03 UTC, FirewallGR commented on Algebra-of-Polynomials/libs/Functional/lib_Monom/Monom.cpp
> +        result.powers[i] /= x;
Зачем делить степень на число

2023-04-03 20:04 UTC, Firstbourne commented on Algebra-of-Polynomials/libs/Functional/lib_Monom/Monom.cpp
> +        throw std::invalid_argument("Different number of variables");
Одно из правил алгебры мономов:
Нельзя умножать моном на моном, содержащий переменные, которых нет в первом мономе. Например, моном x^2 нельзя умножить на моном x^2y.

2023-04-03 20:22 UTC, Firstbourne commented on Algebra-of-Polynomials/libs/Functional/lib_Monom/Monom.cpp
> +        result.powers[i] /= x;
Исправлено

2023-04-03 20:23 UTC, merged